# app/agents/retrieval_agents/greeting_agent.py
from __future__ import annotations
from collections.abc import Mapping
from typing import Any
from pydantic import BaseModel, Field

from app.workflow.retrieval_state import RetrieverState
from app.configs.llm_config import ask_gemini_structured

# Define a strict schema so Gemini drops the text exactly where we need it
class SmallTalkResponse(BaseModel):
    response: str = Field(description="A highly contextual, concise conversational reply to the user.")

class GreetingAgent:
    """Generates fluid, context-aware small talk responses using Gemini."""

    def __init__(self, payload: str | Mapping[str, Any] | RetrieverState):
        self.payload = payload

    def _build_system_prompt(self, intent: str) -> str:
        return f"""You are a polite, helpful corporate AI assistant. 
The user is engaging in conversational small talk, and the system classified their intent specifically as: '{intent}'.

YOUR TASK:
Generate a short, friendly, and natural response matching this intent. Do not offer deep explanations or execute backend database queries. Keep it conversational and brief (1-2 sentences max).

Guidelines based on intent:
- greeting: Say hello warmly and ask how you can help.
- farewell: Wish them well and say goodbye.
- rapport_smalltalk: Answer politely and match their friendly energy.
- gratitude_ack: Accept their thanks gracefully (e.g., 'You're very welcome!').
- apology_ack: Reassure them politely that everything is perfectly fine.
- offtopic_query: Politely remind them that you are an Banking assistant, but handle the turn gracefully.
"""

    def execute(self) -> dict[str, Any]:
        """Return a dynamic conversational response generated by Gemini."""
        if isinstance(self.payload, RetrieverState):
            state = self.payload
            
            # Read the exact intent detected by your ClassifierAgent step
            current_intent = state.intent or "greeting"
            
            system_prompt = self._build_system_prompt(current_intent)
            user_prompt = f"User said: '{state.query}'"
            
            # Call Gemini with structured schema output
            result = ask_gemini_structured(
                system_prompt=system_prompt,
                user_prompt=user_prompt,
                response_schema=SmallTalkResponse
            )
            
            # ✅ Return the dict updating the state.response parameter smoothly!
            return {
                "response": result.get("response")
            }
            
        # Fallback dictionary safety block
        return {"response": "Hello! How can I assist you today?"}
